name = "LiberationBuilder"
prefix = "lbh"
author = "jals-es"
mainprefix = "x"

[files]
include = [
    "mod.cpp",
    "workshop_preview.png"
]

[lints.sqf]
enabled = false

[lints.config]
enabled = false
